apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-efs-fs1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ hostvars['local_machine']['efs_fs1_dnsname'] }}
    path: "/"
