- name: systemd_daemon_reload
  shell: systemctl daemon-reload


- name: restart_etcd_service
# restart etcd service using shell, as a 'systemd' ansible step will block as it waits for etcd to see 3 members
  shell: systemctl restart etcd
  async: 3600
  poll: 0
