- name: build terraform infrastructure on AWS
  terraform:
    binary_path: '{{binary_path}}'
    project_path: '{{project_path}}'
    state: present
  register: terraform_output


- name: sleep to ensure AWS EC2 instances are settled
  pause:
    seconds: 10


- name: Refresh EC2 cache
  command: "{{inventory_dir}}/ec2.py --refresh-cache"
  changed_when: false


- name: Refresh in-memory EC2 cache
  meta: refresh_inventory


- name: get IP addresses of instances via ec2.py script
  debug:
    msg:
      - "kube-master0: {{hostvars[groups['tag_Name_kube_master0'][0]]['ec2_ip_address']}}"
      - "kube-master1: {{hostvars[groups['tag_Name_kube_master1'][0]]['ec2_ip_address']}}"
      - "kube-master2: {{hostvars[groups['tag_Name_kube_master2'][0]]['ec2_ip_address']}}"
      - "kube-node0: {{hostvars[groups['tag_Name_kube_node1'][0]]['ec2_ip_address']}}"
      - "kube-node1: {{hostvars[groups['tag_Name_kube_node1'][0]]['ec2_ip_address']}}"
      - "kube-node2: {{hostvars[groups['tag_Name_kube_node2'][0]]['ec2_ip_address']}}"


# - name: get IP addresses of instances via output from terraform run step
#   debug:
#     msg:
#       - "kube-master0: {{terraform_output.outputs.kubemaster0_ip.value}}"
#       - "kube-master1: {{terraform_output.outputs.kubemaster1_ip.value}}"
#       - "kube-master2: {{terraform_output.outputs.kubemaster2_ip.value}}"
#       - "kube-node0: {{terraform_output.outputs.kubenode0_ip.value}}"
#       - "kube-node1: {{terraform_output.outputs.kubenode1_ip.value}}"
#       - "kube-node2: {{terraform_output.outputs.kubenode2_ip.value}}"


- name: set fact for ID of test1-ebs ({{terraform_output.outputs.test1_ebs_volume_id.value}})
  set_fact:
     test1_ebs_volume_id: "{{terraform_output.outputs.test1_ebs_volume_id.value}}"


- name: set fact for DNSname of test2-efs-fs1 ({{terraform_output.outputs.test2_efs_fs_dnsname.value}})
  set_fact:
     test2_efs_fs_dnsname: "{{terraform_output.outputs.test2_efs_fs_dnsname.value}}"


- name: set fact for DNSname of kubernetes-api-internal-nlb1 ({{terraform_output.outputs.kubernetes_api_internal_nlb1_dnsname.value}})
  set_fact:
     kubernetes_api_internal_nlb1_dnsname: "{{terraform_output.outputs.kubernetes_api_internal_nlb1_dnsname.value}}"
