- name: build terraform infrastructure on AWS
  terraform:
    binary_path: '{{binary_path}}'
    project_path: '{{project_path}}'
    state: present
  register: terraform_output


- name: sleep to ensure AWS EC2 instances are settled
  pause:
    seconds: 10


- name: Refresh EC2 cache
  command: "{{inventory_dir}}/ec2.py --refresh-cache"
  changed_when: false


- name: Refresh in-memory EC2 cache
  meta: refresh_inventory


- name: get IP addresses of instances via ec2.py script
  debug:
    msg:
      - "kube-master1: {{hostvars[groups['tag_Name_kube_master1'][0]]['ec2_ip_address']}}"
      # - "kube-master2: {{hostvars[groups['tag_Name_kube_master2'][0]]['ec2_ip_address']}}"
      - "kube-node1: {{hostvars[groups['tag_Name_kube_node1'][0]]['ec2_ip_address']}}"
      - "kube-node2: {{hostvars[groups['tag_Name_kube_node2'][0]]['ec2_ip_address']}}"


# - name: get IP addresses of instances via output from terraform run step
#   debug:
#     msg:
#       - "kube-master1: {{terraform_output.outputs.kubemaster1_ip.value}}"
#       - "kube-master2: {{terraform_output.outputs.kubemaster2_ip.value}}"
#       - "kube-node1: {{terraform_output.outputs.kubenode1_ip.value}}"
#       - "kube-node2: {{terraform_output.outputs.kubenode2_ip.value}}"


- name: set fact for ID of extra_ebs_volume1 ({{terraform_output.outputs.extra_ebs_volume1_ID.value}})
  set_fact:
     extra_ebs_volume1_ID: "{{terraform_output.outputs.extra_ebs_volume1_ID.value}}"


- name: set fact for DNSname of efs_fs1 ({{terraform_output.outputs.efs_fs1_dnsname.value}})
  set_fact:
     efs_fs1_dnsname: "{{terraform_output.outputs.efs_fs1_dnsname.value}}"


