- name: destroy test helm app
  shell: helm delete --purge test-helm-nginx
  ignore_errors: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf




- name: delete all deployments
  shell: kubectl delete deployments --all
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf


- name: delete all services
  shell: kubectl delete services --all
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf


- name: sleep 12 mins to workaround issue in kubernetes not deleting load balancer -> https://github.com/kubernetes/kubernetes/issues/17626
  pause:
    minutes: 12


- name: delete all replication controllers
  shell: kubectl delete rc --all
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf


- name: delete all pods
  shell: kubectl delete pods --all
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf


- name: delete all PVCs
  shell: kubectl delete pvc --all
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf


- name: delete all PVs
  shell: kubectl delete pv --all
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
