# usage:
# AWS_PROFILE=superman ansible-playbook playbooks/playbook-build-kubernetes-cluster.yml

- hosts: local_machine
  roles:
    - { role: terraform-kubernetes1, project_path: '{{playbook_dir}}/../../terraform/', binary_path: '{{playbook_dir}}/../../terraform/terraform' }


- hosts: tag_Name_kube*
  roles:
    - { role: aws-FQDN-hostname }
    - { role: nfs-client }
    - { role: apt-packages-upgrade }
    - { role: docker, version: "17.03.2~ce-0~debian-stretch" }
    - { role: kubernetes }


- hosts: tag_Name_kube_master0
  roles:
    # - { role: kubernetes-master-HA, etcd_version: 'v3.1.10', cluster_mode: 'primary-master' }
    - { role: kubernetes-master }


# - hosts: tag_Name_kube_master1 tag_Name_kube_master2
#   roles:
#     - { role: kubernetes-master-HA, etcd_version: 'v3.1.10', cluster_mode: 'secondary-master' }


- hosts: tag_Name_kube_node*
  roles:
    - { role: kubernetes-node }


- hosts: tag_Name_kube_master0
  roles:
   - { role: kubernetes-app-test1-ebs }
   - { role: kubernetes-app-test2-efs }

