# usage:
# AWS_PROFILE=superman ansible-playbook playbooks/playbook-build-kubernetes-cluster.yml



# BUILD INFRASTRUCTURE ON AWS WITH TERRAFORM
- hosts: local_machine
  roles:
    - { role: terraform-kubernetes1, project_path: '{{playbook_dir}}/../../terraform/', binary_path: '{{playbook_dir}}/../../terraform/terraform' }



# GENERAL OS SETUP FOR ALL INSTANCES
- hosts: tag_Name_kube*
  roles:
    - { role: aws-FQDN-hostname }
    - { role: nfs-client }
    - { role: apt-packages-upgrade }
    - { role: docker, version: "17.03.2~ce-0~debian-stretch" }
    - { role: kubernetes }


# # # [LEGACY] CREATE NON-HA KUBERNETES MASTER
# # - hosts: tag_Name_kube_master0
# #   roles:
# #     - { role: kubernetes-master }



# CREATE ETCD CLUSTER FOR KUBERNETES
- hosts: tag_Name_kube_master0
  roles:
    - { role: kubernetes-master-HA-etcd, etcd_version: 'v3.1.12', cluster_mode: 'primary-master' }

- hosts: tag_Name_kube_master1 tag_Name_kube_master2
  roles:
    - { role: kubernetes-master-HA-etcd, etcd_version: 'v3.1.12', cluster_mode: 'secondary-master' }



# ADD MASTERS TO KUBERNETES CLUSTER
- hosts: tag_Name_kube_master0
  roles:
    - { role: kubernetes-master-HA, cluster_mode: primary-master }

- hosts: tag_Name_kube_master1 tag_Name_kube_master2
  roles:
    - { role: kubernetes-master-HA, cluster_mode: secondary-master }



# ADD WORKER NODES TO KUBERNETES CLUSTER
- hosts: tag_Name_kube_node*
  roles:
    - { role: kubernetes-node }



# RECONFIGURE KUBE-PROXY TO WORK WITH AWS LB AND INSTALL HELM
- hosts: tag_Name_kube_master0
  roles:
    - { role: kubernetes-master-kube-proxy }
    - { role: kubernetes-helm, helm_version: 'v2.8.2' }



# RUN KUBERNETES TEST APPLICATIONS ON CLUSTER
- hosts: tag_Name_kube_master0
  roles:
   - { role: kubernetes-app-test1-ebs }
   - { role: kubernetes-app-test2-efs }
   - { role: kubernetes-app-test3-helm }
   - { role: kubernetes-app-test4-deployment-with-aws-lb }
