# inspired by: https://ngineered.co.uk/blog/using-amazon-efs-to-persist-and-share-between-conatiners-data-in-kuberneteshttps://ngineered.co.uk/blog/using-amazon-efs-to-persist-and-share-between-conatiners-data-in-kubernetes


- name: create directory kubernetes-yaml-definitions
  file:
    path: /opt/kubernetes-yaml-definitions/
    state: directory


- name: copy pv-efs-fs1 definition file
  template:
    src: pv-efs-fs1.yml
    dest: /opt/kubernetes-yaml-definitions/


- name: check PV list to check if PV already running
  command: kubectl get pv
  register: pv_list
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf


# TODO: use something other than a command step here - maybe native kubernetes step?...
- name: create kubernetes resource from definition file
  command: kubectl create -f /opt/kubernetes-yaml-definitions/pv-efs-fs1.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: '"pv-efs-fs1" not in pv_list.stdout'





- name: copy pvc-efs-fs1 definition file
  template:
    src: pvc-efs-fs1.yml
    dest: /opt/kubernetes-yaml-definitions/


- name: check PVC list to check if PVC already running
  command: kubectl get pvc
  register: pvc_list
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf


# TODO: use something other than a command step here - maybe native kubernetes step?...
- name: create kubernetes resource from definition file
  command: kubectl create -f /opt/kubernetes-yaml-definitions/pvc-efs-fs1.yml
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  when: '"pv-efs-fs1" not in pvc_list.stdout'
