- name: add docker apt repository signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present


- name: add docker apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian stretch stable
    state: present


- name: install prerequisite-software
  package:
    name: "{{item}}"
    state: present
    force: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common


- name: add apt-hold pin to keep docker-ce at version {{version}}
  copy:
    dest: /etc/apt/preferences.d/docker-ce
    content: |
      Package: docker-ce
      Pin: version {{ version }}
      Pin-Priority: 1002


- name: install docker version {{version}}
  apt:
    name: "docker-ce={{version}}"
    state: present


- name: enable docker service
  service:
    name: docker
    enabled: yes
    state: started
    daemon_reload: yes
  ignore_errors: yes
