- name: register FQDN from AWS metadata endpoint
  command: curl 169.254.169.254/latest/meta-data/hostname
  args:
    warn: no
  register: aws_hostname
  changed_when: false


- name: set FQDN hostname to enable kubernetes-aws integration
  hostname:
    name: "{{aws_hostname.stdout}}"
